### ISSUE TITLE
Music stuff

### ISSUE THREAD

**Issue by julientaq** [Spidlace/free-stuff-covid19#1]
Moog et Korg offre des app IOS et Android pour faire de la musique:

## pour IOS

Synthétiseur Model D de Moog
https://apps.apple.com/us/app/minimoog-model-d-synthesizer/id1339418001

iKaossilator de Korg
https://apps.apple.com/us/app/korg-ikaossilator/id452559831

## pour android

Korg Kaossilator
https://play.google.com/store/apps/details?id=jp.co.korg.kaossilator.android&hl=fr

Parfait pour RESTEZ CHEZ VOUS.

**Comment by Spidlace** [comment]
Merci ! :blush:

https://github.com/Spidlace/free-stuff-covid19/commit/571f17d3497c98b8c1e12129fcff44861ef6dcd8
