### ISSUE TITLE
Des jeux gratuit :)

### ISSUE THREAD

**Issue by julientaq** [Spidlace/free-stuff-covid19#2]
Collection de jeu gratuit sur Itch.io, proposé par 

https://twitter.com/iamleyeti/status/1239494887025803265

**Comment by julientaq** [comment]
Tous les jeux de terry cavanagh sont gratuit pour une période limitée: 

https://terrycavanagh.itch.io

**Comment by Spidlace** [comment]
Done 😊
Thanks !!
